version: "3"

services:
  db:
    container_name: base-mysql
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --general_log=ON --bind_address=0.0.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      -  ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
